### ISSUE TITLE
Better code abstraction? 

### ISSUE THREAD

**Issue by Rrraaaeee** [AY2122S1-CS2113T-W13-4/tp#18]
https://github.com/AY2122S1-CS2113T-W13-4/tp/blob/9b1dfc58aba3d3ab094a00e764870ccccd7577dc/src/main/java/cooper/verification/Verifier.java#L29

I think it is generally not recommended to use `instanceof` to check for the child type of the object, since it defeats the purpose of polymorphism where the caller do not need to care about the type. It also looks like `login` and `registration` classes do not have much functionality overlaps as for now. Do you guys think this way of abstraction is necessary??

**Comment by theeugenechong** [comment]
Yes, I thought about this also. It is like this for now because I coded it out based on how I logically planned it in my notebook. 😂 I think I could add an abstract method (something similar to `execute()` in the `Command` class) which performs the necessary action . So the `hasCorrectRole()` method can be private to `Login`.

**Comment by Rrraaaeee** [comment]
No prob! For the MVP definitely we should focus on the functionalities first.
